import { defineCollection, z } from "astro:content";
import { glob } from "astro/loaders";

/**
 * Base schema for content validation
 * 
 * Note: Default values for frontmatter fields are now handled by the
 * remarkFrontmatterDefaults plugin in src/astro/remark/frontmatter-defaults.js
 * 
 * This schema only validates the types and structure of the data.
 */
const baseSchema = z.object({
  title: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  author: z.string().optional().nullable(),
  date: z.coerce.date().optional().nullable(),
  updated: z.coerce.date().optional().nullable(),
  tags: z.array(z.string()).optional().nullable(),
  visibility: z.enum(["public", "unlisted", "private"]).optional(),
  permalink: z.string().optional(),
  layout: z.string().optional().nullable(),
  draft: z.boolean().optional(),
});

const docs = defineCollection({
  loader: glob({ pattern: "**/*.md", base: "./content" }),
  schema: baseSchema,

  /**
   * Transform hook to use permalink as the URL
   * 
   * The permalink is generated by the frontmatter-defaults remark plugin
   * if not explicitly provided in frontmatter. This ensures:
   * - Every document has a consistent URL identifier
   * - URLs can be customized via frontmatter
   * - The URL is accessible as entry.url in templates
   */
  transform: (entry) => {
    // The permalink should always be set by the remark plugin
    // If for some reason it's missing, fall back to the file path
    const url = entry.data.permalink || `/${entry.id.replace(/\.mdx?$/, '')}/`;

    return {
      ...entry,
      url, // Override Astro's auto-generated URL with our permalink
      data: {
        ...entry.data,
        permalink: url, // Keep it in data too for template access
      },
    };
  },
});

export const collections = {
  docs,
};
