import config from "virtual:standard/config";

export async function GET(context) {
    const security = config.security || {};
    if (security.enabled === false) {
        return new Response(null, { status: 404 });
    }

    const defaults = {
        xFrameOptions: "DENY",
        xContentTypeOptions: "nosniff",
        referrerPolicy: "strict-origin-when-cross-origin",
        enableCaching: true,
        csp: {
            defaultSrc: ["'self'"],
            scriptSrc: ["'self'", "'unsafe-inline'"],
            styleSrc: ["'self'", "'unsafe-inline'"],
            imgSrc: ["'self'", "data:", "https:"],
            fontSrc: ["'self'", "data:"],
            connectSrc: ["'self'"],
            frameAncestors: ["'none'"],
        },
        permissions: {
            geolocation: [],
            camera: [],
            microphone: [],
            payment: [],
            usb: [],
        },
    };

    const xFrameOptions = security.xFrameOptions ?? defaults.xFrameOptions;
    const xContentTypeOptions = security.xContentTypeOptions ?? defaults.xContentTypeOptions;
    const referrerPolicy = security.referrerPolicy ?? defaults.referrerPolicy;
    const enableCaching = security.enableCaching ?? defaults.enableCaching;

    const cspConfig = { ...defaults.csp, ...(security.csp || {}) };
    const permissionsConfig = { ...defaults.permissions, ...(security.permissions || {}) };

    const cspDirectives = Object.entries(cspConfig)
        .map(([key, values]) => {
            const directive = key.replace(/([A-Z])/g, "-$1").toLowerCase();
            return `${directive} ${values.join(" ")}`;
        })
        .join("; ");

    const permissionsStr = Object.entries(permissionsConfig)
        .map(([key, values]) => {
            const origins = values.length > 0 ? values.join(" ") : "";
            return `${key}=(${origins})`;
        })
        .join(", ");

    let content = `# Security Headers\n# Generated by Standard Framework\n\n/*\n  X-Frame-Options: ${xFrameOptions}\n  X-Content-Type-Options: ${xContentTypeOptions}\n  Referrer-Policy: ${referrerPolicy}\n  Content-Security-Policy: ${cspDirectives}\n  Permissions-Policy: ${permissionsStr}\n`;

    if (enableCaching) {
        content += `\n# Cache Headers\n/*.css\n  Cache-Control: public, max-age=31536000, immutable\n\n/*.js\n  Cache-Control: public, max-age=31536000, immutable\n\n/*.woff2\n  Cache-Control: public, max-age=31536000, immutable\n`;
    }

    return new Response(content, {
        headers: {
            "Content-Type": "text/plain",
        },
    });
}
